### ISSUE TITLE
Allow for automatic stack traces

### ISSUE THREAD

**Issue by dapper-gh** [ya-sach1/log-smth-ts#5]
Have an option for loggers, e.g. `stack: true` that allows for stack traces to be appended to each log.
To get a stack trace, use the following:
```js
(new Error()).stack
```
One important thing to consider is that any `log-smth`-related functions (used internally) will appear in the stack trace. A nice thing to do would be to automatically detect those `log-smth`-related functions and strip them from the stack trace, and optionally support a feature to strip additional functions from the stack trace (e.g. functions created by the user, like error handlers).

**Comment by ya-sach1** [comment]
Working on it

**Comment by ya-sach1** [comment]
My dumbass forgot to make a PR for it but oh well, I added stack traces.
I'll probably make some kind of support for white-listing which Errors to log, but right now I'm busy with other things.
